export const REQUEST_ALGOLIA = 'REQUEST_ALGOLIA';
export const RECEIVE_ALGOLIA = 'RECEIVE_ALGOLIA';
export const REQUEST_ALGOLIA_FAILED = 'REQUEST_ALGOLIA_FAILED';

export const REQUEST_PUBLIC = 'REQUEST_PUBLIC';
export const RECEIVE_PUBLIC = 'RECEIVE_PUBLIC';
export const REQUEST_PUBLIC_FAILED = 'REQUEST_PUBLIC_FAILED';
